/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AltLogo: typeof import('./components/AltLogo.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ExternalButton: typeof import('./components/ExternalButton.vue')['default']
    HeaderLogo: typeof import('./components/HeaderLogo.vue')['default']
    ImageTrack: typeof import('./components/ImageTrack.vue')['default']
    LocationCell: typeof import('./components/LocationCell.vue')['default']
    NavLink: typeof import('./components/NavLink.vue')['default']
    Polaroid: typeof import('./components/Polaroid.vue')['default']
    RegistryButton: typeof import('./components/RegistryButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RSVPButton: typeof import('./components/RSVPButton.vue')['default']
    SplitFlap: typeof import('./components/SplitFlap.vue')['default']
  }
}
