/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/(details)': RouteRecordInfo<'/(details)', '/', Record<never, never>, Record<never, never>>,
    '/accommodations': RouteRecordInfo<'/accommodations', '/accommodations', Record<never, never>, Record<never, never>>,
    '/our-story': RouteRecordInfo<'/our-story', '/our-story', Record<never, never>, Record<never, never>>,
    '/photos': RouteRecordInfo<'/photos', '/photos', Record<never, never>, Record<never, never>>,
    '/q-and-a': RouteRecordInfo<'/q-and-a', '/q-and-a', Record<never, never>, Record<never, never>>,
    '/registry': RouteRecordInfo<'/registry', '/registry', Record<never, never>, Record<never, never>>,
    '/rsvp': RouteRecordInfo<'/rsvp', '/rsvp', Record<never, never>, Record<never, never>>,
    '/things-to-do': RouteRecordInfo<'/things-to-do', '/things-to-do', Record<never, never>, Record<never, never>>,
    '/wedding-party': RouteRecordInfo<'/wedding-party', '/wedding-party', Record<never, never>, Record<never, never>>,
  }
}
